name: Build Linux Kernel
run-name: "Build Kernel by: @${{ github.actor }}"
on:
  workflow_dispatch:
    inputs:
      tar_url:
        description: "Source Tar URL"
        required: true
        type: string
      packaging:
        description: Packaging Method to Export
        required: true
        type: choice
        options:
        - rpm-pkg            
        - binrpm-pkg
        - deb-pkg
        - bindeb-pkg
        - snap-pkg
        - tar-pkg
        - targz-pkg
        - tarbz2-pkg
        - tarxz-pkg
        - perf-tar-src-pkg
        - perf-targz-src-pkg
        - perf-tarbz2-src-pkg
        - perf-tarxz-src-pkg

jobs:
    build_and_package:
        name: Build Kernel and export
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Download Kernel Source
            run: |
              axel -a -n 8 ${{inputs.tar_url}} --output=kernel_source &&\
              mkdir -p ./build/kernel &&\
              tar -xf kernel_source -C ./build/kernel --strip-components=1

